apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-to-video-api
spec:
  replicas: 3  # Increase replicas for production
  template:
    spec:
      containers:
      - name: api
        resources:
          requests:
            memory: "24Gi"  # Increase memory for production
            cpu: "6"
            nvidia.com/gpu: 2
          limits:
            memory: "48Gi"
            cpu: "12"
            nvidia.com/gpu: 2
        env:
        - name: MAX_CONCURRENT_JOBS
          value: "3"  # More concurrent jobs in production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-to-video-frontend
spec:
  replicas: 3  # Increase frontend replicas for production
  template:
    spec:
      containers:
      - name: frontend
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1" 