apiVersion: v1
kind: ConfigMap
metadata:
  name: text-to-video-config
  namespace: text-to-video
  labels:
    app: text-to-video-api
data:
  # Redis configuration
  REDIS_URL: "redis://redis:6379/0"
  
  # Application configuration
  MAX_CONCURRENT_JOBS: "2"
  MODEL_CACHE_DIR: "/app/model_cache"
  OUTPUT_DIR: "/app/outputs"
  
  # Server configuration
  HOST: "0.0.0.0"
  PORT: "8000"
  WORKERS: "1"
  
  # Model configuration
  MODEL_ID: "genmo/mochi-1-preview" 